### ISSUE TITLE
您好，你在https://github.com/lucas-clemente/quic-go/issues/844 quic-go这个项目的issue里提到了后来找到了bbr的实现，请问实现了bbr的是哪个项目呢？

### ISSUE THREAD

**Issue by longXboy** [vegertar/dnsrouter#1]
您好，你在https://github.com/lucas-clemente/quic-go/issues/844 quic-go这个项目的issue里提到了后来找到了bbr的实现，请问实现了bbr的是哪个项目呢？

**Comment by vegertar** [comment]
不好意思，没说完整。我是指quic-go的开发者已经注意到了需要实现BBR。
https://github.com/lucas-clemente/quic-go/issues/341
